// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owvtcgskljknkzggmrys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93dnRjZ3NrbGprbmt6Z2dtcnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTEwODksImV4cCI6MjA3Mjk4NzA4OX0.Fqrqn0Wa6KYV67Run_D0Fd8abGWBjNAlDFDfI1HUf1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});